In [50]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:4]

array([0, 1, 2, 3])

In [7]:
arr[:4]

array([0, 1, 2, 3])

In [9]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<p style="
          color: white; 
          background-color: red; 
          padding: 20px; 
          box-shadow: 0px 8px 20px #FF0000AA; 
          margin: 20px; width: 90%; 
          border-radius: 8px; 
          text-align:center;
          font-size: 1.8rem;
          font-family: Manrope, Helvetica Neue, Helvetica, Segoe UI, Arial, sans-serif;
          font-weight: 700;
          ">NOTE: NUMPY JUST REFERENCES COPIES!!!</p>
It doesn't create a copy.

In [13]:
slice_of_arr = arr[:6]

In [15]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:5] = 99
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<hr>

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[1][2]

30

SAME AS

In [26]:
arr_2d[1,2]

30

In [28]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [27]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Conditional Selection

In [35]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [39]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [40]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [44]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])